name: lzf
description: >
  A Dart implementation of the LZF, a fast, lightweight compression algorithm
  optimized for speed.
version: 0.1.1
repository: https://github.com/halildurmus/lzf
issue_tracker: https://github.com/halildurmus/lzf/issues
funding:
  - https://github.com/sponsors/halildurmus

topics:
  - lzf
  - compression

environment:
  sdk: ^3.11.0

dev_dependencies:
  checks: ^0.3.1
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  test: ^1.29.0
