name: lzf
description: TODO
version: 0.1.0
repository: https://github.com/halildurmus/lzf
issue_tracker: https://github.com/halildurmus/lzf/issues
funding:
  - https://github.com/sponsors/halildurmus

environment:
  sdk: ^3.7.0

dev_dependencies:
  checks: ^0.3.0

  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints

  test: ^1.25.15
